# Generated by Django 5.2.14 on 2026-06-04 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('age', models.IntegerField(verbose_name='Edad')),
                ('condition', models.CharField(max_length=200, verbose_name='Diagnóstico / Condición')),
                ('last', models.CharField(blank=True, max_length=100, verbose_name='Última atención')),
                ('initials', models.CharField(blank=True, max_length=10, verbose_name='Iniciales')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=10, verbose_name='Hora (ej. 09:00)')),
                ('type', models.CharField(max_length=100, verbose_name='Tipo de cita')),
                ('status', models.CharField(default='Confirmada', max_length=50, verbose_name='Estado')),
                ('zoom_link', models.URLField(blank=True, default='', verbose_name='Enlace de Zoom')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patient', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
            },
        ),
    ]
