# Generated by Django 6.0.6 on 2026-06-04 18:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='code',
            field=models.CharField(blank=True, max_length=8, unique=True, verbose_name='Codigo de revision'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha'),
        ),
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Correo electronico'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='condition',
            field=models.CharField(max_length=200, verbose_name='Diagnostico / Condicion'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ultima atencion'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('date', 'time'), name='unique_appointment_slot'),
        ),
    ]
