# Generated by Django 6.0.6 on 2026-06-04 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_appointment_code_appointment_date_patient_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='Titulo')),
                ('summary', models.CharField(max_length=260, verbose_name='Resumen')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('published', models.BooleanField(default=True, verbose_name='Publicado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Publicacion',
                'verbose_name_plural': 'Publicaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='OZONO SALUD', max_length=140, verbose_name='Titulo')),
                ('about', models.TextField(default='Consulta medica en linea con atencion cercana, organizada y segura.', verbose_name='Quienes somos')),
                ('mission', models.TextField(blank=True, verbose_name='Mision / mensaje principal')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Telefono')),
                ('address', models.CharField(blank=True, max_length=180, verbose_name='Direccion')),
            ],
            options={
                'verbose_name': 'Informacion del sitio',
                'verbose_name_plural': 'Informacion del sitio',
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='clinical_notes',
            field=models.TextField(blank=True, verbose_name='Notas de la consulta'),
        ),
    ]
