# Generated by Django 6.0.6 on 2026-06-04 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_publication_siteprofile_appointment_clinical_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprofile',
            name='facebook_url',
            field=models.URLField(default='https://www.facebook.com/ozonosaludmantaec', verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='instagram_url',
            field=models.URLField(default='https://www.instagram.com/ozono_salud_/', verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='zoom_url',
            field=models.URLField(blank=True, verbose_name='Cuenta o enlace de Zoom'),
        ),
    ]
