# Generated by Django 6.0.6 on 2026-06-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_siteprofile_facebook_url_siteprofile_instagram_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="exam_order",
            field=models.TextField(blank=True, verbose_name="Orden de examen"),
        ),
        migrations.AddField(
            model_name="appointment",
            name="prescription",
            field=models.TextField(blank=True, verbose_name="Recetario"),
        ),
        migrations.AddField(
            model_name="publication",
            name="image_url",
            field=models.URLField(blank=True, verbose_name="Link de imagen"),
        ),
    ]
