# Generated by Django 6.0.6 on 2026-06-05 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_appointment_exam_order_appointment_prescription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='image',
            field=models.FileField(blank=True, upload_to='publications/', verbose_name='Imagen'),
        ),
    ]
