# Generated by Django 6.0.6 on 2026-06-09 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_publication_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprofile',
            name='doctor_name',
            field=models.CharField(blank=True, max_length=140, verbose_name='Nombre del doctor'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='logo',
            field=models.FileField(blank=True, upload_to='site/', verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='tagline',
            field=models.CharField(default='Tu salud en buenas manos', max_length=160, verbose_name='Frase de marca'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='watermark',
            field=models.FileField(blank=True, upload_to='site/', verbose_name='Marca de agua'),
        ),
    ]
