# Generated by Codex on 2026-06-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_siteprofile_doctor_name_siteprofile_logo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="certificate_patient_id",
            field=models.CharField(blank=True, max_length=20, verbose_name="Cedula del paciente"),
        ),
        migrations.AddField(
            model_name="appointment",
            name="certificate_reason",
            field=models.TextField(blank=True, verbose_name="Razon del certificado medico"),
        ),
    ]
